name: kanban-dashboard
recipe: laravel
config:
  via: nginx
  webroot: api/public
  database: mysql:8.0
  php: '8.2'
  config:
    vhosts: .lando/nginx.conf

services:
  appserver:
    build_as_root:
      - apt-get update -y
      - cd api && composer install
  database:
    portforward: 49220
    run_as_root:
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS kanban_admin;"
  node:
    type: node:16.13
    build_as_root:
      - cd app && yarn install

proxy:
  appserver_nginx:
    - "kanbandash.lndo.site"
    - "*.kanbandash.lndo.site"

tooling:
  redis-cli:
    service: cache
  node:
    service: node
  npm:
    service: node
  yarn:
    service: node
    description: "Run Yarn command"
