name: kanban-dashboard
recipe: laravel
config:
  via: nginx
  webroot: public
  database: mysql:8.0
  php: '8.1'

services:
  appserver:
    build_as_root:
      - apt-get update -y
  database:
    portforward: 49220
    run_as_root:
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS kanban_dasboard;"
